### PR TITLE
Problem in testing

### PR DESCRIPTION
**Pull request by spyp**
I try test this package in fresh laravel 5.7
But I git problem. TestCase inside package is not working at all.
and i think its not good that we have two Tests\TestCase one in package and one in laravel tests folder 

So i change it and problem solved .
If i'm wrong tell me about it .

### CODE REVIEW

**Comment by dwightwatson** [comment]
Oh whoops, that didn’t even occur to me. 

Would it be better to just re-namespace the base TestCase to Watson so it matches the source code? I think it’s good to still have a base TestCase as it separates the configuration from the tests.

**Comment by spyp** [comment]
good idea let me check it.

**Comment by spyp** [comment]
I have problem that take couple of hours :)
I change compoer.json file in autoload-dev and set
```json
"autoload-dev": {
        "psr-4": {
            "Watson\\Aggregate\\Tests\\": "tests"
        }
    },
```
and change namespaces of test file AggregateTest and TestCase
but when i update compoesr and composer.lock and ....
i have error when i run tests that 
Watson\Aggregate\Tests\TestCase not found

I don't know where i goes wrong.If you have idea tell me about it.

**Comment by dwightwatson** [comment]
When you run `composer install` it automatically caches any of the namespaces you have defined. So when you updated the `psr-4` namespace there Composer won't automatically see it.

If you run `composer dump-autoload` it'll force Composer to check out the autoload directories again and then everything should work.

**Comment by dwightwatson** [comment]
Just pushed this up against master as to fix the issue in a tagged release - should all be working as expected now!

**Pull request closed without merging**
